#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dynamic_Controler.Resource", IsApplication=true)]

namespace Dynamic_Controler
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int rotate_centre = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Back_Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Image_Logo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Off_Enable = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int On_Enable = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Refresh_Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Refresh_Icon_2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Splash_Screen_Horizontal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Splash_Screen_Vertical = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int btnBack = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int btnRefresh = 2131230722;
			
			// aapt resource value: 0x7f08000d
			public const int btncontroller = 2131230733;
			
			// aapt resource value: 0x7f08000a
			public const int btnrefresh = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int btnscandevice = 2131230729;
			
			// aapt resource value: 0x7f08001f
			public const int buttonPrompt = 2131230751;
			
			// aapt resource value: 0x7f080023
			public const int editTextDialogUserInput = 2131230755;
			
			// aapt resource value: 0x7f080020
			public const int editTextResult = 2131230752;
			
			// aapt resource value: 0x7f080017
			public const int flowlabel = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int flowresult = 2131230744;
			
			// aapt resource value: 0x7f080011
			public const int humiditylabel = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int humidityresult = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int imageView1 = 2131230727;
			
			// aapt resource value: 0x7f080021
			public const int layout_root = 2131230753;
			
			// aapt resource value: 0x7f080003
			public const int listDevice = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int mainlayout = 2131230725;
			
			// aapt resource value: 0x7f080024
			public const int nameDevice = 2131230756;
			
			// aapt resource value: 0x7f08000e
			public const int parameters = 2131230734;
			
			// aapt resource value: 0x7f080004
			public const int scrollView1 = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int searchlayout = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int statuslabel = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int statuslayout = 2131230731;
			
			// aapt resource value: 0x7f080010
			public const int tableRow1 = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int tableRow2 = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int tableRow3 = 2131230742;
			
			// aapt resource value: 0x7f080019
			public const int tableRow4 = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int tableRow5 = 2131230748;
			
			// aapt resource value: 0x7f08000f
			public const int tblparameters = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int temperaturelabel = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int temperatureresult = 2131230741;
			
			// aapt resource value: 0x7f080022
			public const int textView1 = 2131230754;
			
			// aapt resource value: 0x7f08001d
			public const int timelabel = 2131230749;
			
			// aapt resource value: 0x7f08001e
			public const int timeresult = 2131230750;
			
			// aapt resource value: 0x7f080006
			public const int title = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int title_text = 2131230720;
			
			// aapt resource value: 0x7f08001a
			public const int todaylabel = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int todayresult = 2131230747;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Custom_Actionbar_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int List_Device_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int prompts = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int prompts_text = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int row_In_List_Device = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int menu_device = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Example = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
